select * from espacios_deportivos;

select * from establecimientos_deportivos;


INSERT INTO `db_gtics`.`establecimientos_deportivos` 
(
    `establecimiento_deportivo`, 
    `descripcion`, 
    `direccion`, 
    `espacios_estacionamiento`, 
    `telefono_contacto`, 
    `correo_contacto`, 
    `geolocalizacion`, 
    `foto_establecimiento_url`, 
    `horario_apertura`, 
    `horario_cierre`, 
    `estado`, 
    `motivo_mantenimiento`, 
    `fecha_creacion`, 
    `fecha_actualizacion`
) 
VALUES 
('Polideportivo San Isidro', 
 'Polideportivo ubicado en San Isidro con múltiples canchas y espacios para diversos deportes.',
 'Av. Ejemplo 123, San Isidro, Lima', 
 25, 
 '987654321', 
 'contacto@sanisidro.pe', 
 '-12.04318,-77.02824', 
 'https://example.com/images/sanisidro.jpg', 
 '08:00', 
 '22:00', 
 'activo', 
 NULL, 
 NOW(), 
 NOW()),

('Estadio Municipal Surco', 
 'Estadio con capacidad para 20,000 personas, ideal para eventos deportivos y conciertos.',
 'Jr. Futbol 456, Surco, Lima', 
 40, 
 '912345678', 
 'info@surco.gob.pe', 
 '-12.04350,-77.02900', 
 'https://example.com/images/surco.jpg', 
 '07:00', 
 '21:00', 
 'activo', 
 NULL, 
 NOW(), 
 NOW()),

('Complejo Deportivo San Borja', 
 'Complejo con canchas de tenis, gimnasio y piscina olímpica.',
 'Av. San Borja Sur 789, San Borja, Lima', 
 15, 
 '987654322', 
 'contacto@sanborja.pe', 
 '-12.04400,-77.03100', 
 'https://example.com/images/sanborja.jpg', 
 '06:00', 
 '23:00', 
 'activo', 
 NULL, 
 NOW(), 
 NOW()),

('Estadio Nacional de Lima', 
 'Estadio principal de Perú, usado para partidos de fútbol, conciertos y otros eventos.',
 'Av. José Díaz 100, Lima', 
 50, 
 '987654323', 
 'info@estadiolima.pe', 
 '-12.04700,-77.02800', 
 'https://example.com/images/estadonacional.jpg', 
 '09:00', 
 '23:00', 
 'activo', 
 NULL, 
 NOW(), 
 NOW()),

('Complejo Deportivo Villa El Salvador', 
 'Instalaciones deportivas de calidad en el sur de Lima con canchas y gimnasio.',
 'Av. César Vallejo 456, Villa El Salvador', 
 30, 
 '987654324', 
 'contacto@villaelsalvador.pe', 
 '-12.15500,-77.00100', 
 'https://example.com/images/villaelsalvador.jpg', 
 '08:00', 
 '21:00', 
 'activo', 
 NULL, 
 NOW(), 
 NOW()),

('Club Deportivo Barranco', 
 'Club con piscina, canchas de fútbol y otras instalaciones deportivas.',
 'Av. Bolognesi 123, Barranco, Lima', 
 20, 
 '987654325', 
 'info@barranco.pe', 
 '-12.13000,-77.03400', 
 'https://example.com/images/barranco.jpg', 
 '06:00', 
 '22:00', 
 'activo', 
 NULL, 
 NOW(), 
 NOW()),

('Estadio de la Universidad Nacional Agraria La Molina', 
 'Estadio universitario con canchas y otros espacios deportivos para la comunidad.',
 'Av. La Molina 789, La Molina, Lima', 
 10, 
 '987654326', 
 'contacto@l Molina.pe', 
 '-12.02200,-77.02700', 
 'https://example.com/images/lm.jpg', 
 '07:00', 
 '20:00', 
 'activo', 
 NULL, 
 NOW(), 
 NOW()),

('Polideportivo de Miraflores', 
 'Polideportivo con diversas actividades y canchas de uso público.',
 'Av. Pardo 1234, Miraflores, Lima', 
 40, 
 '987654327', 
 'contacto@miraflores.pe', 
 '-12.11500,-77.02800', 
 'https://example.com/images/miraflores.jpg', 
 '06:00', 
 '22:00', 
 'activo', 
 NULL, 
 NOW(), 
 NOW()),

('Complejo Deportivo San Miguel', 
 'Complejo deportivo para fútbol, tenis, y otros deportes.',
 'Av. San Miguel 1010, San Miguel, Lima', 
 35, 
 '987654328', 
 'info@sanmigueldpe.pe', 
 '-12.05000,-77.06000', 
 'https://example.com/images/sanmiguel.jpg', 
 '08:00', 
 '20:00', 
 'activo', 
 NULL, 
 NOW(), 
 NOW()),

('Club Deportivo El Cercado', 
 'Un centro deportivo con espacio para partidos, entrenamientos y más.',
 'Jr. Dos de Mayo 789, El Cercado, Lima', 
 25, 
 '987654329', 
 'contacto@elcercado.pe', 
 '-12.05000,-77.04000', 
 'https://example.com/images/elcercado.jpg', 
 '07:00', 
 '23:00', 
 'activo', 
 NULL, 
 NOW(), 
 NOW());

